

package smstrProject;

import java.awt.*;
import java.awt.print.*;
import java.time.LocalDate;

public class printInvoice implements Printable {

    private String invoiceText;

    public printInvoice() {
          StringBuilder sb = new StringBuilder();
        sb.append("            INVOICE         \n");
        sb.append("Date: ").append(LocalDate.now()).append("\n");
        sb.append("Generated By: Zaman Medical Store \n\n");
        sb.append(String.format("%-15s %-20s %-10s %-10s\n", "Medicine ID", "Name", "Qty", "Price"));
        sb.append("-----------------------------------------------------------\n");
        
        for (String[] med : invoice.medicines) {
            sb.append(String.format("%-15s %-20s %-10s %-10s\n", 
                med[0], med[1], med[2], med[3]));
        }
        sb.append("\nTotal: ").append(invoice.getTotal()).append("\n");
        invoiceText = sb.toString();

     
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(this);
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }
    }

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) return NO_SUCH_PAGE;
        
        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        g2d.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        int y = 20;
        for (String line : invoiceText.split("\n")) {
            g2d.drawString(line, 20, y);
            y += 15;
        }
        return PAGE_EXISTS;
    }
}